export default [
    {
        id:1,
        name:"discover",
        link:"#discover",
        image:"/card_image/discover.png"
    },
    {
        id:2,
        name:"mastercard",
        link:"#mastercard",
        image:"/card_image/mastercard.png"
    },
    {
        id:3,
        name:"paypal",
        link:"#paypal",
        image:"/card_image/paypal.png"
    },
    {
        id:1,
        name:"paysafe",
        link:"#paysafe",
        image:"/card_image/paysafe.png"
    },{
        id:1,
        name:"visa",
        link:"#visa",
        image:"/card_image/visa.png"
    },
    
]